### ISSUE TITLE
libboost issue after installation

### ISSUE THREAD

**Issue by alexeyovchinnikov** [bertiniteam/b2#167]
Running bertini2 returns the following error:

./bertini2: error while loading shared libraries: libboost_filesystem.so.1.79.0: cannot open shared object file: No such file or directory

However, libboost_filesystem.so.1.79.0 in the bash path.

bertini2 is installed locally, in ~/bin

**Comment by ofloveandhate** [comment]
This was probably an issue with making sure that boost's path is on  `LD_RUN_PATH`.  closing.  feel free to re-open if still interested, or this comes up again.
