### ISSUE TITLE
Error using default constructor for node types

### ISSUE THREAD

**Issue by jbcolli2** [bertiniteam/b2#20]
For all operator nodes, such as SumOperator, PowerOperator, ExpOperator, Function, ...  they have default constructors and so it is possible to create an empty operator.  Then, a EXC_BAD_ACCESS runtime error occurs when the following code is run:

```
	std::shared_ptr<Variable> x = std::make_shared<Variable>("x");
	std::shared_ptr<Node> f = std::make_shared<AOperator>();
	f += x;
	std::cout << f->Eval<dbl>() << std::endl;
```

Such a piece of code makes most sense when `AOperator` is `Function` or perhaps `SumOperator`.  I have done some tests and found that this error occurs when `AOperator` is the following operators:

`Function`
`NegateOperator`
`PowerOperator`
`IntegerPowerOperator`
`SqrtOperator`
`ExpOperator`
`LogOperator`
`SinOperator`
I haven't tested all the other trig operators, but I think we can safely assume they act like `SinOperator`.  I have also not looked at `Jacobian`.

**Comment by ofloveandhate** [comment]
I have been able to replicate this problem, and will work on fixing it.  thanks jeb!

**Comment by ofloveandhate** [comment]
I have addressed this problem, and the solution is present in a pull request from one of my branches into the bertiniteam/develop branch.
