### ISSUE TITLE
Bertini hangs when run in parallel

### ISSUE THREAD

**Issue by adamjstewart** [bertiniteam/b2#27]
I'm trying to install Bertini for a user and I'm running into a problem. After downloading the MPI2 version of Bertini for 64 bit Linux (either 1.4.1 or 1.5) and extracting it, I try the following commands:
```bash
mpirun -np 1 bertini -help
mpirun -np 2 bertini -help
```
The first command completes successfully. However, when I run the second command, it prints the help message, but afterwards hangs and never returns control to the command line. Is this expected behavior? I'm not sure if there's a better way to test the software than this.

**Comment by aliddell** [comment]
This is the expected behavior. From the original developer: "only the head node check for the '-help' command and exits while the workers wait to perform computations." This is to show that the individual workers are created (i.e., MPI is working properly).

**Comment by adamjstewart** [comment]
@aliddell: Thanks for the good news!
