### ISSUE TITLE
Location of Eigen library

### ISSUE THREAD

**Issue by rideckardtest** [bertiniteam/b2#36]
Hi Guys,

I have just a small observation from compiling on linux. When you have Eigen installed in /usr/local/Eigen (not "eigen3/Eigen") the configure script doesn't find it. So you should maybe edit the ax_eigen macro to include something like
```
 for ac_eigen_path_tmp in /usr /usr/local /opt /opt/local ; do
            if test -d "$ac_eigen_path_tmp/include/eigen3/Eigen"; then
                EIGEN_CPPFLAGS="-I$ac_eigen_path_tmp/include/eigen3"
                found_eigen_dir=yes;
                break;
	    elif test -d "$ac_eigen_path_tmp/include/Eigen"; then
                EIGEN_CPPFLAGS="-I$ac_eigen_path_tmp/include"
                found_eigen_dir=yes;
                break;
            fi
 done
```
Also if you compile the tests, in complex_test.cpp you have
`#include <eigen3/Eigen/Dense>` instead of  `#include <Eigen/Dense>`
This did it for me. Hope I'm not going on your nerves. I would have done a pull-request but seems silly for something so small.

**Comment by bertiniteam** [comment]
thanks a lot!!!  

done.  please pull from master (this is what you're testing, right?  it doesn't matter right now, because master and develop are in sync), and recheck.  if it fixes, close.  thanks!!!

**Comment by rideckardtest** [comment]
Works...and closing.
