### ISSUE TITLE
MPFR parser issue with scientific notation

### ISSUE THREAD

**Issue by jbcolli2** [bertiniteam/b2#37]
The MPFR parser within function_parsers.hpp does not read scientific notation correctly.  In general it will skip over the scientific portion of the notation.  Also, if no decimal is in the number, scientific notation cannot be used.

In addition, this parser is needed for other components and so should be separated off to it's own struct so it is accessible by other parsers.

**Comment by ofloveandhate** [comment]
hey jeb, this was fixed,  right?  will reference the PR that fixes this?

**Comment by jbcolli2** [comment]
Fixed in PR #39
