### ISSUE TITLE
Check for consistent use of p-norms

### ISSUE THREAD

**Issue by timothodge** [bertiniteam/b2#54]
Core development team has decided to use the L infinity norm instead of the L2 norm. Consistent use of the lpNorm<Infinity>() functionality inside of the core needs to be checked. 

 in eigen i.e.,  "lpNorm<Infinity>()"

**Comment by ofloveandhate** [comment]
so far, i have ensured that the cauchy endgame uses the infinity-norm.  other places might still use the 2-norm

**Comment by ofloveandhate** [comment]
i think this is fixed.  i'm closing it.
