### ISSUE TITLE
Compiling with Eigen3.3_beta2

### ISSUE THREAD

**Issue by fpancald** [bertiniteam/b2#56]
Today I tried to compile the current version of b2/master using Eigen3.3_beta2 as part of the linear algebra timing comparison between b1 and b2.

Also using boost/1.61 and gcc/4.9.2, all other dependencies versions are in the configuration file.

I am creating issue under @ofloveandhate suggestion. 

Code compiles fine but when trying tests I get the output in the Eigen_3.3._beta_error.txt file, ot looks like is choking on the eigen test.
I am also including configuration file.
[configure_b2_beta.txt](https://github.com/bertiniteam/b2/files/482962/configure_b2_beta.txt)
[Eigen_3_3_beta2_error.txt](https://github.com/bertiniteam/b2/files/482963/Eigen_3_3_beta2_error.txt)

Has anyone compiled against this Eigen version? What is the highest version you successfully compiled against?

**Comment by ofloveandhate** [comment]
i think this is the same issue as discussed in [this kde forum post](https://forum.kde.org/viewtopic.php?f=74&t=133404&p=359710#p358419) from july.  so, hypothetically, it is fixed.  i will try compiling tomorrow, and see if it passes.  we might have to wait for beta3 or a release candidate, depending on Eigen release patterns.

**Comment by ofloveandhate** [comment]
i confirm this problem with compiling against Eigen 3.3_beta2, and with the official repo's current state, Rev 9564.  i will raise this issue with the Eigen team on KDE, and post a link to that from here.

**Comment by ofloveandhate** [comment]
following up on KDE forum posting about this, the policy for questions /  bugs / feature requests has changed.  it looks like ggael is asking people to use SO for questions, the bugtracker for bugs (makes sense!), and mailing lists for features.  see [this](https://forum.kde.org/viewtopic.php?f=74&t=134953).

so, if i am unable to resolve this myself, i will go to SO for help, then to the bugtracker if we did indeed find another bug.

**Comment by ofloveandhate** [comment]
this compilation problem was my fault.  i had incorrectly declared the Eigen::NumTraits for expressions of mpfr_floats.  Commit d1b7f6a3f3b25741e5fe14c183637488ca19db00 fixes this.  @fpancald will you please confirm?  i tested Eigen 3.3_beta2, Rev 9564 from the hg repo, and 3.2.9 on my Mac with the XCode-provided Clang.

**Comment by fpancald** [comment]
I confirm it now works on the ND crc system. All tests compile and execute. I got 5 pass and 2 fails (pool_test and endgames_test). @ofloveandhate  can you confirm that is how it's supposed to be at this point of the development?

**Comment by ofloveandhate** [comment]
yes.  i'm closing this issue.
