### ISSUE TITLE
Error compiling python bindings 

### ISSUE THREAD

**Issue by camer1kj** [bertiniteam/b2#57]
Hey b2 team,

The core is successfully compiled, but I am running into some issues with the python buildings. 
Following the steps from the READ ME: 

After `libtoolize` I get the message: 
"Remember to add `AC_PROG_LIBTOOL' to`configure.ac'".

After `autoreconf -fi` I get the error: 
"configure.ac:13: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1"

I added the AC_PROG_LIBTOOL macro, just to see what would happen, but nothing changes. 
Thanks for your help, 

Karleigh

**Comment by ofloveandhate** [comment]
can you please indicate your operating system, compiler and version, and
versions of automake and autoconf?

**Comment by camer1kj** [comment]
Ubuntu 16.04
g++ 5.4.0

Automake 1.15
Autoconf 2.69

**Comment by ofloveandhate** [comment]
Is this on the master branch?

**Comment by ofloveandhate** [comment]
Hi Karleigh, 
libtoolize worked fine in a just-installed ubuntu 16.04.  Maybe you have an old version?
`sudo apt-get install libtool` should bring you to version 2.4.6.

**Comment by ofloveandhate** [comment]
Yep, @camer1kj , `libtool` is the culprit.  i got the same errors from `autoreconf` when i uninstalled libtool.  re-installed, and the errors go away.  your version is our of date.

please confirm, and close if successful.

**Comment by camer1kj** [comment]
Thanks @ofloveandhate. There was an issue with `libtool` - I had already installed it with `apt-get` and thus it was the most recent version, but it was not being detected. After moving some things around that problem should be fixed. 
(From b2/python `libtool` is detected with version 2.4.6)
However- I still get the same error after `autoreconf` about undefined macro..

**Comment by ofloveandhate** [comment]
Hmm.  in my just-installed ubuntu 16.04, with apt-get installed versions of autoconf, automake, and libtool, this step works fine for me...

try `sudo apt-get install pkg-config`

**Comment by camer1kj** [comment]
Already the newest version...

My ubuntu is also just installed. I think the problem I am having is stemming from originally installling autoconf,automake, etc. manually instead of using apt-get... After switching to apt-get to make sure I get all the dependencies, it seems like my system isn't detecting the new versions unless I move them over to usr/local/bin where my manually installed versions were located. Maybe the best answer is to start over...

**Comment by ofloveandhate** [comment]
am i correct also in assuming you are on the master branch?

**Comment by ofloveandhate** [comment]
nuke the system and start over. if you don't already use a separate
partition for your os vs your home, now is a good time to start.

**Comment by ofloveandhate** [comment]
thanks.  i will try to replicate the problem.

**Comment by camer1kj** [comment]
Already the newest version...

My ubuntu is also just installed. I think the problem I am having is
stemming from originally installling autoconf,automake, etc. manually
instead of using apt-get... After switching to apt-get to make sure I get
all the dependencies, it seems like my system isn't detecting the new
versions unless I move them over to usr/local/bin where my manually
installed versions were located. Maybe the best answer is to start over...

**Comment by camer1kj** [comment]
Yes, I am on the master branch.. I'll start over. Thanks for the help.

**Comment by camer1kj** [comment]
Update: I decided to just wipe my Ubuntu and start over.

I installed ubuntu on my old partition, apt-get installed `automake`, `autoconf`, `libtool`, `boost`, and `eigen`, and cloned the b2 repository.

Then `libtoolize -fi`, `autoreconf -fi` went fine. At` ./configure` I got a few issues with dependencies I still needed (gmp and mpfr), which I downloaded, along with `libboost-all-dev` in case there were more libraries I needed.

Then,` ./configure` also was fine.

BUT : `make -j `completely froze my computer and printed the error: "virtual memory exhausted, cannot allocate memory"

By suggestion of @ofloveandhate I changed it to '`make -j 2`' and all was fine, core was compiled successfully. 

Python also proceeded without issue until '`make -j 2`' again, were I get the following issue : 

```
/usr/local/include/bertini2/tracking/amp_cauchy_endgame.hpp:292:28:   required from here
/usr/local/include/bertini2/tracking/tracking_config.hpp:252:74: internal compiler error: in tsubst_copy, at cp/pt.c:13039
     T final_tolerance_times_final_tolerance_multiplier = final_tolerance * final_tolerance_multiplier;
```

Any idea?

**Comment by ofloveandhate** [comment]
Ewww...  internal compiler error.  This seems to be evidence of perhaps [this](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54844) bug?  What version of gcc are you using?  `gcc --version`, please.

I think I remember getting this error once upon a time.

**Comment by camer1kj** [comment]
gcc 5.4.0

**Comment by ofloveandhate** [comment]
thanks.  let me see if i can replicate on my VM ubuntu 16.04.

**Comment by ofloveandhate** [comment]
i'm struggling to get it to accept my bertini2 lib, configure for pybertini is failing at that step...  did you do anything special to get it to find bertini2?  argh, i thought i fixed this problem!!!  i like autotools less and less as time goes on.  anyone care to CMake this project for me / us?

**Comment by camer1kj** [comment]
Nope, mine configured fine... :/

**Comment by camer1kj** [comment]
Nope, mine configured fine... :/

**Comment by ofloveandhate** [comment]
i think this was my fault, with several versions of boost installed things are fighting with each other.

**Comment by ofloveandhate** [comment]
ok, i have generated your error.  my stupid problems were my own fault, and were due to having installed multiple versions of boost. 

now to fix the problem...  i suspect this line of code is no good regardless of this gcc bug, so i think the best solution might be to eliminate it.  i will play around.  thanks for being patient, @camer1kj

**Comment by ofloveandhate** [comment]
@camer1kj I have fixed the problem.  i changed it to just use a default value, rather than an arithmetic result.  compilation now succeeds in ubuntu 16.04.  please pull and recompile

**important note**  
someone insanely decided to ship a beta version of Eigen through apt-get.  when you install eigen through apt-get, you currently get 3.2.92, which is a beta.  this beta has some bugs which affect compilation of the python bindings.

i suggest you `sudo apt-get remove libeigen-dev` and manually download release candidate 2, or 3.2.10.  then, you can either move them into a suitably named folder in `/usr/local/include`, or use the `./configure --with-eigen=/path/to/eigen` option.

you will have to re-compile the core, if you previously used the apt-get version of eigen.  that's the way with header-only libraries.  recompile the world if things change.

if you wish to confirm the version of eigen you have, it's at `eigen3/Eigen/src/Core/util/Macros.h`.  3.2.95 is the most current release candidate, I believe.  3.2.92 is old, and won't work for PyBertini.

**Comment by camer1kj** [comment]
FYI When I recompile after the pull, with eigen 3.2.10, I get 4 instances of the following error: 
```
In file included from ./include/bertini2/mpfr_complex.hpp:37:0,
                 from src/basics/mpfr_complex.cpp:1:
./include/bertini2/mpfr_extensions.hpp:187:30: error: ‘boost::multiprecision::max’ has not been declared
 using boost::multiprecision::max; //3 options: ./configure --disable-expression_templates, use Boost 1.61, or patch earlier Boost versions to resolve this.
```
Looks like we might need to update to the new boost?

**Comment by ofloveandhate** [comment]
either that, or disable expression templates like the error says... ;)

**Comment by camer1kj** [comment]
Disabled expression templates and have success until the python tests: 

```
python: /usr/local/include/bertini2/tracking/base_endgame.hpp:241: bertini::tracking::SuccessCode bertini::tracking::endgame::EndgameBase<TrackerType, FinalEGT>::ComputeInitialSamples(const CT&, bertini::Vec<CT>&, bertini::tracking::TimeCont<CT>&, bertini::tracking::SampCont<CT>&) [with CT = bertini::complex; TrackerType = bertini::tracking::AMPTracker; FinalEGT = bertini::tracking::endgame::AMPCauchyEndgame; bertini::Vec<CT> = Eigen::Matrix<bertini::complex, -1, 1, 0, -1, 1>; bertini::tracking::TimeCont<CT> = std::deque<bertini::complex, std::allocator<bertini::complex> >; bertini::tracking::SampCont<CT> = std::deque<Eigen::Matrix<bertini::complex, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<bertini::complex, -1, 1, 0, -1, 1> > >]: Assertion `Precision(start_time)==Precision(x_endgame) && "Computing initial samples requires input time and space with uniform precision"' failed.
Aborted (core dumped)

```

**Comment by ofloveandhate** [comment]
well, we're through the compiling part of this issue.  you are compiled, and the new issue is this failing test due to non-uniform precision of samples.  i'm closing this, and asking you to post a new issue regarding this test error.  thanks @camer1kj
