### ISSUE TITLE
./configure fails: "fail to find gmp" mac osx

### ISSUE THREAD

**Issue by davisbnag** [bertiniteam/b2#58]
I've been going through the README instructions. I believe I have gone through the dependencies section and I am trying to run:

```./configure --disable-thread_local```

I get this message: 
`configure: error: unable to find gmp`

 first tried:

```brew install gmp```

and got the message:

`Warning: gmp-6.1.1 already installed`

I then checked for gmp in /usr/local and found a gmp folder in:
`/usr/local/Cellar`

**Comment by ofloveandhate** [comment]
Thanks for the issue report.  Let's check whether the compiler can see the libraries you have installed.

Try compiling a little test program, manually linking to gmp.

```
#include <iostream>
#include <gmp.h>
int main()
{
	std::cout << "hi brent\n";
	return 0;
}
```

the line to compile should be 

```
g++ source.cpp -lgmp
```

Will you please test compile, and report back?

**Comment by davisbnag** [comment]
I tried this and it could link without adding the full path during compiling.

**Comment by ofloveandhate** [comment]
this is evidence of the compiler not knowing where to look, but `/usr/local` is a standard location.  i remember encountering this a few semesters ago with a Scientific Computing student.  

[here](http://stackoverflow.com/questions/23905661/on-mac-g-clang-fails-to-search-usr-local-include-and-usr-local-lib-by-def)'s a link to an SO post addressing this problem.  Briefly, you need to install the command line tools:
```
xcode-select --install
```

**Comment by davisbnag** [comment]
I tried this, it installed and then ./configure worked. Thank you!
